language: java
sudo: false
install: true
addons:
  coveralls:
    token:
      secure: "${COVERALLS_REPO_TOKEN}"
  sonarcloud:
    organization: avexis
    token:
      secure: "${SONAR_TOKEN}"
branches:
  only:
  - master
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar jacoco:report coveralls:report
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"